from __future__ import annotations

import json
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak,
    KeepTogether,
)

BASE_DIR = Path(__file__).resolve().parents[3]
DATA_DIR = BASE_DIR / "data"
REPORT_DIR = BASE_DIR / "reports"

REPORT_DIR.mkdir(parents=True, exist_ok=True)


def _load_analysis(case_id: str) -> dict:
    path = DATA_DIR / f"{case_id}_analysis.json"

    if not path.exists():
        raise FileNotFoundError(
            f"Analysis not found for case {case_id}"
        )

    with path.open("r", encoding="utf-8") as f:
        return json.load(f)


def _text(value) -> str:
    if value is None:
        return "Not detected"
    return str(value)


def _yes_no(value) -> str:
    return "Yes" if value else "No"


def _p(value, style):
    text = str(value)

    # Escape normal text first.
    text = (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )

    # Restore only the markup intentionally generated by this report.
    text = text.replace("&lt;b&gt;", "<b>")
    text = text.replace("&lt;/b&gt;", "</b>")
    text = text.replace("&lt;br/&gt;", "<br/>")

    text = text.replace("\n", "<br/>")

    return Paragraph(text, style)


def _table(rows, widths, header=True):
    table = Table(
        rows,
        colWidths=widths,
        repeatRows=1 if header else 0,
        splitByRow=1,
        hAlign="LEFT",
    )

    commands = [
        (
            "BOX",
            (0, 0),
            (-1, -1),
            0.6,
            colors.HexColor("#cbd5e1"),
        ),
        (
            "INNERGRID",
            (0, 0),
            (-1, -1),
            0.35,
            colors.HexColor("#dbe2ea"),
        ),
        (
            "VALIGN",
            (0, 0),
            (-1, -1),
            "TOP",
        ),
        (
            "TOPPADDING",
            (0, 0),
            (-1, -1),
            7,
        ),
        (
            "BOTTOMPADDING",
            (0, 0),
            (-1, -1),
            7,
        ),
        (
            "LEFTPADDING",
            (0, 0),
            (-1, -1),
            7,
        ),
        (
            "RIGHTPADDING",
            (0, 0),
            (-1, -1),
            7,
        ),
    ]

    if header:
        commands.extend(
            [
                (
                    "BACKGROUND",
                    (0, 0),
                    (-1, 0),
                    colors.HexColor("#17345f"),
                ),
                (
                    "TEXTCOLOR",
                    (0, 0),
                    (-1, 0),
                    colors.white,
                ),
            ]
        )
    else:
        commands.append(
            (
                "BACKGROUND",
                (0, 0),
                (0, -1),
                colors.HexColor("#f4f6f8"),
            )
        )

    table.setStyle(TableStyle(commands))
    return table


def _header_footer(canvas, doc):
    canvas.saveState()

    width, height = A4

    canvas.setStrokeColor(colors.HexColor("#dbe2ea"))
    canvas.line(
        17 * mm,
        height - 13 * mm,
        width - 17 * mm,
        height - 13 * mm,
    )

    canvas.setFont("Helvetica-Bold", 8)
    canvas.setFillColor(colors.HexColor("#17345f"))
    canvas.drawString(
        17 * mm,
        height - 10 * mm,
        "SecureMailScope",
    )

    canvas.setFont("Helvetica", 7)
    canvas.setFillColor(colors.HexColor("#667085"))
    canvas.drawRightString(
        width - 17 * mm,
        height - 10 * mm,
        "Cryptographic Security Posture Assessment",
    )

    canvas.line(
        17 * mm,
        11 * mm,
        width - 17 * mm,
        11 * mm,
    )

    canvas.setFont("Helvetica", 7)
    canvas.setFillColor(colors.HexColor("#667085"))
    canvas.drawString(
        17 * mm,
        7 * mm,
        "Generated from analyzed PCAP evidence",
    )

    canvas.drawRightString(
        width - 17 * mm,
        7 * mm,
        f"Page {doc.page}",
    )

    canvas.restoreState()


def generate_pdf_report(case_id: str) -> Path:
    payload = _load_analysis(case_id)

    case = payload["case"]
    analysis = payload["analysis"]

    posture = analysis.get("posture", {})
    session = (
        analysis.get("sessions", [{}])[0]
        if analysis.get("sessions")
        else {}
    )

    starttls = session.get("starttls") or {}
    tls = session.get("tls") or {}
    cert = tls.get("certificate") or {}
    ml = session.get("ml") or {}
    findings = analysis.get("findings", [])

    output_path = REPORT_DIR / f"{case_id}-security-assessment.pdf"

    doc = SimpleDocTemplate(
        str(output_path),
        pagesize=A4,
        leftMargin=17 * mm,
        rightMargin=17 * mm,
        topMargin=20 * mm,
        bottomMargin=17 * mm,
        title=f"SecureMailScope - {case_id}",
        author="SecureMailScope",
    )

    styles = getSampleStyleSheet()

    title = ParagraphStyle(
        "Title",
        parent=styles["Title"],
        fontName="Helvetica-Bold",
        fontSize=22,
        leading=26,
        alignment=TA_CENTER,
        textColor=colors.HexColor("#17345f"),
        spaceAfter=4 * mm,
    )

    subtitle = ParagraphStyle(
        "Subtitle",
        parent=styles["Normal"],
        fontSize=9,
        leading=12,
        alignment=TA_CENTER,
        textColor=colors.HexColor("#667085"),
        spaceAfter=8 * mm,
    )

    section = ParagraphStyle(
        "Section",
        parent=styles["Heading2"],
        fontName="Helvetica-Bold",
        fontSize=13,
        leading=16,
        textColor=colors.HexColor("#17345f"),
        spaceBefore=5 * mm,
        spaceAfter=3 * mm,
    )

    body = ParagraphStyle(
        "Body",
        parent=styles["BodyText"],
        fontName="Helvetica",
        fontSize=8.5,
        leading=12,
        textColor=colors.HexColor("#273444"),
        splitLongWords=True,
    )

    small = ParagraphStyle(
        "Small",
        parent=body,
        fontSize=7.5,
        leading=10.5,
    )

    label = ParagraphStyle(
        "Label",
        parent=body,
        fontName="Helvetica-Bold",
        textColor=colors.HexColor("#526174"),
    )

    table_head = ParagraphStyle(
        "TableHead",
        parent=body,
        fontName="Helvetica-Bold",
        fontSize=7.5,
        leading=9.5,
        textColor=colors.white,
    )

    table_cell = ParagraphStyle(
        "TableCell",
        parent=body,
        fontSize=7.6,
        leading=10,
        splitLongWords=True,
    )

    table_label = ParagraphStyle(
        "TableLabel",
        parent=table_cell,
        fontName="Helvetica-Bold",
        textColor=colors.HexColor("#334155"),
    )

    finding_title = ParagraphStyle(
        "FindingTitle",
        parent=body,
        fontName="Helvetica-Bold",
        fontSize=9,
        leading=12,
        textColor=colors.HexColor("#172033"),
    )

    story = []

    story.append(Paragraph("SecureMailScope", title))
    story.append(
        Paragraph(
            "Cryptographic Security Posture Assessment Report",
            subtitle,
        )
    )

    score = posture.get("score", 0)
    posture_name = _text(posture.get("posture"))

    score_table = Table(
        [
            [
                _p("SECURITY POSTURE", label),
                _p(f"{score} / 100", label),
                _p(posture_name, label),
            ]
        ],
        colWidths=[60 * mm, 40 * mm, 68 * mm],
    )

    score_table.setStyle(
        TableStyle(
            [
                (
                    "BACKGROUND",
                    (0, 0),
                    (-1, -1),
                    colors.HexColor("#eef4fb"),
                ),
                (
                    "BOX",
                    (0, 0),
                    (-1, -1),
                    0.8,
                    colors.HexColor("#bdd0e8"),
                ),
                (
                    "INNERGRID",
                    (0, 0),
                    (-1, -1),
                    0.4,
                    colors.HexColor("#d5e0ed"),
                ),
                (
                    "ALIGN",
                    (1, 0),
                    (-1, -1),
                    "CENTER",
                ),
                (
                    "VALIGN",
                    (0, 0),
                    (-1, -1),
                    "MIDDLE",
                ),
                (
                    "TOPPADDING",
                    (0, 0),
                    (-1, -1),
                    11,
                ),
                (
                    "BOTTOMPADDING",
                    (0, 0),
                    (-1, -1),
                    11,
                ),
            ]
        )
    )

    story.append(score_table)
    story.append(Spacer(1, 4 * mm))

    story.append(Paragraph("1. Case Information", section))

    case_rows = [
        [_p("Field", table_head), _p("Observed Value", table_head)],
        [_p("Case ID", table_label), _p(_text(case.get("case_id")), table_cell)],
        [_p("Source File", table_label), _p(_text(case.get("filename")), table_cell)],
        [_p("SHA-256", table_label), _p(_text(case.get("sha256")), table_cell)],
        [_p("Packets Analyzed", table_label), _p(_text(analysis.get("packet_count")), table_cell)],
        [_p("Sessions", table_label), _p(_text(analysis.get("session_count")), table_cell)],
        [_p("Protocol", table_label), _p(_text(session.get("protocol")), table_cell)],
        [_p("Endpoints", table_label), _p("<br/>".join(session.get("endpoints", [])), table_cell)],
    ]

    story.append(
        _table(
            case_rows,
            [45 * mm, 123 * mm],
            header=True,
        )
    )

    story.append(Paragraph("2. STARTTLS State Assessment", section))

    starttls_rows = [
        [
            _p("State", table_head),
            _p("Observed", table_head),
            _p("Evidence", table_head),
        ],
        [
            _p("Advertised", table_cell),
            _p(_yes_no(starttls.get("advertised")), table_cell),
            _p(", ".join(map(str, starttls.get("evidence", {}).get("advertised_packets", []))) or "-", table_cell),
        ],
        [
            _p("Requested", table_cell),
            _p(_yes_no(starttls.get("requested")), table_cell),
            _p(", ".join(map(str, starttls.get("evidence", {}).get("requested_packets", []))) or "-", table_cell),
        ],
        [
            _p("Accepted", table_cell),
            _p(_yes_no(starttls.get("accepted")), table_cell),
            _p(", ".join(map(str, starttls.get("evidence", {}).get("accepted_packets", []))) or "-", table_cell),
        ],
        [
            _p("TLS Upgrade", table_cell),
            _p(_yes_no(starttls.get("upgraded")), table_cell),
            _p(", ".join(map(str, starttls.get("evidence", {}).get("tls_packets", []))) or "-", table_cell),
        ],
        [
            _p("Final State", table_label),
            _p(_text(starttls.get("final_state")), table_cell),
            _p("-", table_cell),
        ],
    ]

    story.append(
        _table(
            starttls_rows,
            [50 * mm, 40 * mm, 78 * mm],
        )
    )

    tls_section = []

    tls_section.append(
        Paragraph(
            "3. TLS / Cryptographic Configuration",
            section,
        )
    )

    tls_rows = [
        [_p("Parameter", table_head), _p("Observed Value", table_head)],
        [_p("Negotiated TLS Version", table_label), _p(_text(tls.get("negotiated_version")), table_cell)],
        [_p("Cipher Suite", table_label), _p(_text(tls.get("selected_cipher_suite")), table_cell)],
        [_p("Key Exchange", table_label), _p(_text(tls.get("key_exchange")), table_cell)],
        [_p("Forward Secrecy", table_label), _p("Enabled" if tls.get("forward_secrecy") else "Unavailable", table_cell)],
        [_p("Server Name", table_label), _p(_text(tls.get("server_name")), table_cell)],
        [_p("TLS Records", table_label), _p(_text(tls.get("record_count")), table_cell)],
    ]

    tls_section.append(
        _table(
            tls_rows,
            [58 * mm, 110 * mm],
        )
    )

    story.append(KeepTogether(tls_section))

    story.append(Paragraph("4. X.509 Certificate", section))

    if cert:
        cert_rows = [
            [_p("Field", table_head), _p("Observed Value", table_head)],
            [_p("Subject", table_label), _p(_text(cert.get("subject")), table_cell)],
            [_p("Issuer", table_label), _p(_text(cert.get("issuer")), table_cell)],
            [_p("Common Name", table_label), _p(_text(cert.get("common_name")), table_cell)],
            [_p("SAN DNS Names", table_label), _p(", ".join(cert.get("san_dns_names", [])) or "-", table_cell)],
            [_p("Valid From", table_label), _p(_text(cert.get("not_before")), table_cell)],
            [_p("Valid Until", table_label), _p(_text(cert.get("not_after")), table_cell)],
            [_p("Expired", table_label), _p(_yes_no(cert.get("expired")), table_cell)],
            [_p("SHA-256 Fingerprint", table_label), _p(_text(cert.get("sha256_fingerprint")), table_cell)],
        ]

        story.append(
            _table(
                cert_rows,
                [58 * mm, 110 * mm],
            )
        )
    else:
        story.append(
            Paragraph(
                "No X.509 certificate was observed in the analyzed evidence.",
                body,
            )
        )

    story.append(Paragraph("5. AI Anomaly Assessment", section))

    ml_rows = [
        [_p("Metric", table_head), _p("Observed Value", table_head)],
        [_p("Model", table_label), _p(_text(ml.get("model")), table_cell)],
        [_p("Classification", table_label), _p(_text(ml.get("classification")), table_cell)],
        [_p("Anomaly", table_label), _p(_yes_no(ml.get("is_anomaly")), table_cell)],
        [_p("Anomaly Strength", table_label), _p(_text(ml.get("anomaly_strength")), table_cell)],
        [_p("Raw Model Score", table_label), _p(_text(ml.get("raw_model_score")), table_cell)],
    ]

    story.append(
        _table(
            ml_rows,
            [58 * mm, 110 * mm],
        )
    )

    if ml.get("note"):
        story.append(Spacer(1, 2 * mm))
        story.append(_p(ml.get("note"), small))

    story.append(PageBreak())

    story.append(Paragraph("6. Security Findings", section))

    if not findings:
        story.append(
            Paragraph(
                "<b>No security findings were detected.</b>",
                body,
            )
        )
    else:
        for index, finding in enumerate(findings, start=1):
            severity = _text(finding.get("severity"))
            title_text = _text(finding.get("title"))
            finding_id = _text(finding.get("id"))

            story.append(
                Paragraph(
                    f"{index}. [{severity}] {title_text} ({finding_id})",
                    finding_title,
                )
            )

            story.append(
                _p(
                    f"<b>Description:</b> {_text(finding.get('description'))}",
                    body,
                )
            )

            story.append(
                _p(
                    f"<b>Remediation:</b> {_text(finding.get('remediation'))}",
                    body,
                )
            )

            packets = finding.get("evidence_packets", [])
            packet_text = ", ".join(f"#{p}" for p in packets) or "-"

            story.append(
                _p(
                    f"<b>Evidence Packets:</b> {packet_text}    "
                    f"<b>Confidence:</b> {_text(finding.get('confidence'))}",
                    small,
                )
            )

            story.append(Spacer(1, 4 * mm))

    story.append(Paragraph("7. Posture Summary", section))

    summary = posture.get("summary", {})

    summary_rows = [
        [_p("Severity", table_head), _p("Count", table_head)],
        [_p("Critical", table_label), _p(_text(summary.get("critical", 0)), table_cell)],
        [_p("High", table_label), _p(_text(summary.get("high", 0)), table_cell)],
        [_p("Medium", table_label), _p(_text(summary.get("medium", 0)), table_cell)],
        [_p("Low", table_label), _p(_text(summary.get("low", 0)), table_cell)],
        [_p("Total Findings", table_label), _p(_text(summary.get("total", 0)), table_cell)],
    ]

    story.append(
        _table(
            summary_rows,
            [100 * mm, 68 * mm],
        )
    )

    story.append(Spacer(1, 6 * mm))

    story.append(
        _p(
            "This assessment was generated from passive PCAP evidence. "
            "The AI anomaly output is advisory and complements deterministic "
            "security rules. Evidence references identify observed packet numbers "
            "associated with the findings.",
            small,
        )
    )

    doc.build(
        story,
        onFirstPage=_header_footer,
        onLaterPages=_header_footer,
    )

    return output_path
